# Dockerfile used to build the foxsec-pipeline image.
#
# This is the complete image, based off the base image but also containing
# source code and compiled classes.

FROM foxsec-pipeline-base:latest

COPY . /root/project

RUN mvn javadoc:javadoc && mvn compile
RUN cd contrib && GO111MODULE=on GOPROXY=https://proxy.golang.org \
	go get ./... && \
	go mod vendor && \
	(cd auth0pull && go mod vendor && go build) && \
	(cd cloudtrail-streamer && go mod vendor && go build) && \
	(cd duopull && go mod vendor && go build) && \
	(cd slackbot-background && go mod vendor && go build) && \
	(cd slackbot-http && go mod vendor && go build)
RUN mkdir -p /app && cp version.json /app/version.json

ENV FOXSEC_PIPELINE_IMAGE complete
ENTRYPOINT ["/docker-entrypoint.sh"]
