# Dockerfile used to build the foxsec-pipeline-base image.
#
# The base image contains the required daemons/emulators for running tests
# but does not contain any source code or compiled pipeline classes.
#
# The base image is intended to work in conjunction with bin/m and is used
# for development/testing. The base image also forms the basis for the complete
# image which is self-contained.

FROM maven:3-jdk-11

ENV FOXSEC_PIPELINE_IMAGE=base \
	PATH="/root/google-cloud-sdk/bin:/usr/local/go/bin:${PATH}" \
	GOPATH=/root/go

RUN apt-get update -y && \
	apt-get upgrade -y && \
	apt-get install netcat redis-server build-essential \
	memcached --no-install-recommends -y && \
	curl -L https://dl.google.com/go/go1.16.linux-amd64.tar.gz | \
	(cd /usr/local && tar -zxf -) && \
	curl -sSL https://sdk.cloud.google.com | \
	CLOUDSDK_CORE_DISABLE_PROMPTS=1 bash && \
	gcloud config set project foxsec-pipeline && \
	CLOUDSDK_CORE_DISABLE_PROMPTS=1 gcloud components install cloud-datastore-emulator \
	pubsub-emulator beta && \
	GO111MODULE=on go get go.mozilla.org/iprepd/cmd/iprepd && \
	mkdir -p /etc/iprepd

COPY docker/iprepd.yaml /etc/iprepd/iprepd.yaml
COPY docker-entrypoint.sh /

WORKDIR /root/project
ENTRYPOINT ["/docker-entrypoint.sh"]
