package com.mozilla.secops.parser;

import java.io.Serializable;
import org.apache.beam.sdk.metrics.Counter;
import org.apache.beam.sdk.metrics.Metrics;

/** Beam metrics generated by various parser functions */
public class ParserMetrics implements Serializable {
  private static final long serialVersionUID = 1L;

  /** Prefix for metrics namespace component */
  public static final String NAMESPACE_PREFIX = "parser_";

  /** Custom metric name for event too old errors */
  public static final String METRIC_EVENT_TOO_OLD = "event_too_old";

  private final Counter metricEventTooOld;
  private final String namespace;

  /** Event was too old */
  public void eventTooOld() {
    metricEventTooOld.inc();
  }

  /**
   * Create new ParserMetrics
   *
   * @param namespacePostfix String to be appended to NAMESPACE_PREFIX for namespace, null for
   *     default
   */
  public ParserMetrics(String namespacePostfix) {
    if (namespacePostfix == null) {
      namespace = NAMESPACE_PREFIX + "default";
    } else {
      namespace = NAMESPACE_PREFIX + namespacePostfix;
    }
    metricEventTooOld = Metrics.counter(namespace, METRIC_EVENT_TOO_OLD);
  }
}
