package com.mozilla.secops.gatekeeper;

import static org.junit.Assert.*;

import com.mozilla.secops.TestUtil;
import com.mozilla.secops.alert.Alert;
import com.mozilla.secops.input.Input;
import java.io.IOException;
import java.util.Arrays;
import org.apache.beam.sdk.coders.StringUtf8Coder;
import org.apache.beam.sdk.options.PipelineOptionsFactory;
import org.apache.beam.sdk.testing.PAssert;
import org.apache.beam.sdk.testing.TestPipeline;
import org.apache.beam.sdk.testing.TestStream;
import org.apache.beam.sdk.transforms.Count;
import org.apache.beam.sdk.values.PCollection;
import org.joda.time.Instant;
import org.junit.Rule;
import org.junit.Test;

public class TestGatekeeper {
  @Rule public final transient TestPipeline p = TestPipeline.create();

  private TestStream<String> getTestStream() throws IOException {
    String[] gd = TestUtil.getTestInputArray("/testdata/gatekeeper/guardduty-sample-findings.txt");
    String[] etd = TestUtil.getTestInputArray("/testdata/gatekeeper/etd-sample-findings.txt");
    return TestStream.create(StringUtf8Coder.of())
        .advanceWatermarkTo(new Instant(0L))
        .addElements(gd[0], Arrays.copyOfRange(gd, 1, gd.length))
        .advanceWatermarkTo(new Instant(180000L))
        .addElements(etd[0], Arrays.copyOfRange(etd, 1, etd.length))
        .advanceWatermarkToInfinity();
  }

  private GatekeeperPipeline.GatekeeperOptions getBaseTestOptions() {
    GatekeeperPipeline.GatekeeperOptions opts =
        PipelineOptionsFactory.as(GatekeeperPipeline.GatekeeperOptions.class);
    opts.setUseEventTimestamp(true);
    opts.setMonitoredResourceIndicator("gatekeeper-test");
    return opts;
  }

  public TestGatekeeper() {}

  @Test
  public void gatekeeperNoFiltersTest() throws Exception {
    GatekeeperPipeline.GatekeeperOptions opts = getBaseTestOptions();
    opts.setInputFile(
        new String[] {
          "./target/test-classes/testdata/gatekeeper/guardduty-sample-findings.txt",
          "./target/test-classes/testdata/gatekeeper/etd-sample-findings.txt"
        });
    opts.setGenerateConfigurationTicksInterval(1);
    opts.setGenerateConfigurationTicksMaximum(5L);

    PCollection<String> input =
        p.apply(
            "input",
            Input.compositeInputAdapter(opts, GatekeeperPipeline.buildConfigurationTick(opts)));

    PCollection<Alert> alerts = GatekeeperPipeline.executePipeline(p, input, opts);

    PCollection<Long> count = alerts.apply(Count.globally());
    PAssert.that(count).containsInAnyOrder(27L);

    PAssert.that(alerts)
        .satisfies(
            x -> {
              for (Alert a : x) {
                assertNotNull(a.getCategory());
                if (a.getCategory().equals("gatekeeper:aws")) {
                  assertEquals(Alert.AlertSeverity.CRITICAL, a.getSeverity());
                  assertTrue(
                      a.getSummary().startsWith("suspicious activity detected in aws account"));
                  assertEquals("123456789012", a.getMetadataValue("aws_account"));
                  assertEquals("us-west-2", a.getMetadataValue("aws_region"));

                  assertEquals("guardduty", a.getMetadataValue("aws_service"));
                  assertNotNull(a.getMetadataValue("finding_first_seen_at"));
                  assertNotNull(a.getMetadataValue("finding_last_seen_at"));
                  // all findings in sample data have a count of 2
                  assertEquals("2", a.getMetadataValue("finding_count"));
                  assertEquals(
                      "955624e422acc98f6cdb16ab4ab41d23", a.getMetadataValue("aws_gd_detector_id"));

                  // the sample data was produced by clicking on "generate sample data" in the
                  // console and capturing those findings -- and removing any identifiable
                  // information from them. All of the sample findings contain the following
                  // metadata. It is possible that this is not true for all possible findings
                  // generated by guardduty.
                  switch (a.getMetadataValue("finding_type")) {
                    case "NETWORK_CONNECTION":
                      assertNotNull(a.getMetadataValue("network_connection_direction"));
                      assertNotNull(a.getMetadataValue("network_connection_proto"));
                      assertNotNull(a.getMetadataValue("network_connection_blocked"));
                      assertNotNull(a.getMetadataValue("local_port"));
                      assertNotNull(a.getMetadataValue("remote_port"));
                      assertNotNull(a.getMetadataValue("remote_ip_address"));
                      assertNotNull(a.getMetadataValue("remote_ip_country"));
                      assertNotNull(a.getMetadataValue("remote_ip_city"));
                      assertNotNull(a.getMetadataValue("remote_ip_latitude"));
                      assertNotNull(a.getMetadataValue("remote_ip_longitude"));
                      assertNotNull(a.getMetadataValue("remote_ip_asn"));
                      assertNotNull(a.getMetadataValue("remote_ip_asn_org"));
                      assertNotNull(a.getMetadataValue("remote_ip_isp"));
                      assertNotNull(a.getMetadataValue("remote_ip_org"));
                      break;
                    case "AWS_API_CALL":
                      assertNotNull(a.getMetadataValue("api_name"));
                      assertNotNull(a.getMetadataValue("api_service_name"));
                      assertNotNull(a.getMetadataValue("api_caller_type"));
                      assertNotNull(a.getMetadataValue("api_domain_name"));
                      assertNotNull(a.getMetadataValue("remote_ip_address"));
                      assertNotNull(a.getMetadataValue("remote_ip_country"));
                      assertNotNull(a.getMetadataValue("remote_ip_city"));
                      assertNotNull(a.getMetadataValue("remote_ip_latitude"));
                      assertNotNull(a.getMetadataValue("remote_ip_longitude"));
                      assertNotNull(a.getMetadataValue("remote_ip_asn"));
                      assertNotNull(a.getMetadataValue("remote_ip_asn_org"));
                      assertNotNull(a.getMetadataValue("remote_ip_isp"));
                      assertNotNull(a.getMetadataValue("remote_ip_org"));
                      break;
                    case "DNS_REQUEST":
                      assertNotNull(a.getMetadataValue("domain_name"));
                      break;
                    case "PORT_PROBE":
                      assertNotNull(a.getMetadataValue("port_probe_blocked"));
                      assertNotNull(a.getMetadataValue("local_port"));
                      assertNotNull(a.getMetadataValue("remote_port"));
                      assertNotNull(a.getMetadataValue("remote_ip_address"));
                      assertNotNull(a.getMetadataValue("remote_ip_country"));
                      assertNotNull(a.getMetadataValue("remote_ip_city"));
                      assertNotNull(a.getMetadataValue("remote_ip_latitude"));
                      assertNotNull(a.getMetadataValue("remote_ip_longitude"));
                      assertNotNull(a.getMetadataValue("remote_ip_asn"));
                      assertNotNull(a.getMetadataValue("remote_ip_asn_org"));
                      assertNotNull(a.getMetadataValue("remote_ip_isp"));
                      assertNotNull(a.getMetadataValue("remote_ip_org"));
                      break;
                  }
                  assertNotNull(a.getMetadataValue("resource_type"));
                  switch (a.getMetadataValue("resource_type")) {
                    case "AccessKey":
                      assertNotNull(a.getMetadataValue("access_key_id"));
                      assertNotNull(a.getMetadataValue("principal_id"));
                      assertNotNull(a.getMetadataValue("user_name"));
                      assertNotNull(a.getMetadataValue("user_type"));
                      break;
                    case "Instance":
                      assertNotNull(a.getMetadataValue("instance_availability_zone"));
                      assertNotNull(a.getMetadataValue("instance_image_description"));
                      assertNotNull(a.getMetadataValue("instance_image_id"));
                      assertNotNull(a.getMetadataValue("instance_id"));
                      assertNotNull(a.getMetadataValue("instance_state"));
                      assertNotNull(a.getMetadataValue("instance_type"));
                      assertNotNull(a.getMetadataValue("instance_launch_time"));
                      break;
                  }
                } else if (a.getCategory().equals("gatekeeper:gcp")) {
                  assertEquals(Alert.AlertSeverity.CRITICAL, a.getSeverity());
                  assertTrue(a.getSummary().startsWith("suspicious activity detected in gcp org"));
                  // the three project numbers in the sample data
                  assertTrue(
                      a.getMetadataValue("project_number").equals("123456789012")
                          || a.getMetadataValue("project_number").equals("123456785822")
                          || a.getMetadataValue("project_number").equals("123456789210"));
                  assertEquals("audit_log", a.getMetadataValue("indicator"));
                  assertEquals("persistence", a.getMetadataValue("technique"));
                  assertNotNull(a.getMetadataValue("detection_priority"));
                  assertNotNull(a.getMetadataValue("detection_timestap"));
                  assertNotNull(a.getMetadataValue("org_number"));

                  switch (a.getMetadataValue("rule_name")) {
                    case "iam_anomalous_grant":
                      assertNotNull(a.getMetadataValue("evidence_insert_id"));
                      assertNotNull(a.getMetadataValue("evidence_timestamp"));
                      break;
                    case "malware_bad_domain":
                    case "phishing_bad_domain":
                    case "cryptomining_pool_domain":
                      assertNotNull(a.getMetadataValue("evidence_insert_id"));
                      assertNotNull(a.getMetadataValue("evidence_timestamp"));
                      assertNotNull(a.getMetadataValue("domain"));
                      break;
                    case "malware_bad_ip":
                    case "phishing_bad_ip":
                    case "cryptomining_pool_ip":
                      assertNotNull(a.getMetadataValue("evidence_insert_id"));
                      assertNotNull(a.getMetadataValue("evidence_timestamp"));
                      assertNotNull(a.getMetadataValue("ip"));
                      break;
                    case "outgoing_dos":
                      assertNotNull(a.getMetadataValue("subnetwork_id"));
                      assertNotNull(a.getMetadataValue("subnetwork_name"));
                  }
                } else if (a.getMetadataValue("category").equals("cfgtick")) {
                  assertEquals(Alert.AlertSeverity.INFORMATIONAL, a.getSeverity());
                  assertEquals("gatekeeper-cfgtick", a.getCategory());
                  assertEquals("5", a.getMetadataValue("generateConfigurationTicksMaximum"));
                  assertEquals(
                      "Alerts are generated based on events sent from AWS's Guardduty.",
                      a.getMetadataValue("heuristic_GenerateGDAlerts"));
                  assertEquals(
                      "Alerts are generated based on events sent from GCP's Event Threat Detection.",
                      a.getMetadataValue("heuristic_GenerateETDAlerts"));

                } else {
                  fail(String.format("unexpected alert category type: %s", a.getCategory()));
                }
              }
              return null;
            });

    p.run().waitUntilFinish();
  }

  @Test
  public void gatekeeperTestEnrichedGDAlertsWithoutIdentityMgr() throws Exception {
    TestStream<String> s = getTestStream();
    GatekeeperPipeline.GatekeeperOptions opts = getBaseTestOptions();

    PCollection<Alert> alerts = GatekeeperPipeline.executePipeline(p, p.apply(s), opts);

    PAssert.that(alerts)
        .satisfies(
            x -> {
              for (Alert a : x) {
                assertNotNull(a.getCategory());
                if (a.getCategory().equals("gatekeeper:aws")) {
                  assertNull(a.getMetadataValue("aws_account_name"));
                }
              }
              return null;
            });

    p.run().waitUntilFinish();
  }

  @Test
  public void gatekeeperTestEnrichedGDAlertsWithIdentityMgr() throws Exception {
    TestStream<String> s = getTestStream();
    GatekeeperPipeline.GatekeeperOptions opts = getBaseTestOptions();

    // load identity manager containing mapping for all accounts in test data
    opts.setIdentityManagerPath("/testdata/identitymanager.json");

    PCollection<Alert> alerts = GatekeeperPipeline.executePipeline(p, p.apply(s), opts);

    PAssert.that(alerts)
        .satisfies(
            x -> {
              for (Alert a : x) {
                assertNotNull(a.getCategory());
                if (a.getCategory().equals("gatekeeper:aws")) {
                  assertEquals("mock-aws-account-name", a.getMetadataValue("aws_account_name"));
                }
              }
              return null;
            });

    p.run().waitUntilFinish();
  }

  @Test
  public void gatekeeperIgnoreAllETDTest() throws Exception {
    TestStream<String> s = getTestStream();
    GatekeeperPipeline.GatekeeperOptions opts = getBaseTestOptions();
    opts.setIgnoreETDFindingRuleRegex(new String[] {".+"});

    PCollection<Alert> alerts = GatekeeperPipeline.executePipeline(p, p.apply(s), opts);

    PCollection<Long> count = alerts.apply(Count.globally());
    PAssert.that(count).containsInAnyOrder(19L);

    PAssert.that(alerts)
        .satisfies(
            x -> {
              for (Alert a : x) {
                assertNotNull(a.getCategory());
                assertEquals("gatekeeper:aws", a.getCategory());
                assertTrue(
                    a.getSummary().startsWith("suspicious activity detected in aws account"));
                assertEquals("123456789012", a.getMetadataValue("aws_account"));
                assertEquals("us-west-2", a.getMetadataValue("aws_region"));
                assertEquals(Alert.AlertSeverity.CRITICAL, a.getSeverity());
              }
              return null;
            });

    p.run().waitUntilFinish();
  }

  @Test
  public void gatekeeperIgnoreAllGDTest() throws Exception {
    TestStream<String> s = getTestStream();
    GatekeeperPipeline.GatekeeperOptions opts = getBaseTestOptions();
    opts.setIgnoreGDFindingTypeRegex(new String[] {".+"});

    PCollection<Alert> alerts = GatekeeperPipeline.executePipeline(p, p.apply(s), opts);

    PCollection<Long> count = alerts.apply(Count.globally());
    PAssert.that(count).containsInAnyOrder(3L);

    PAssert.that(alerts)
        .satisfies(
            x -> {
              for (Alert a : x) {
                assertNotNull(a.getCategory());
                assertEquals(Alert.AlertSeverity.CRITICAL, a.getSeverity());
                assertEquals("gatekeeper:gcp", a.getCategory());
                assertTrue(a.getSummary().startsWith("suspicious activity detected in gcp org"));
                // the three project numbers in the sample data
                assertTrue(
                    a.getMetadataValue("project_number").equals("123456789012")
                        || a.getMetadataValue("project_number").equals("123456785822")
                        || a.getMetadataValue("project_number").equals("123456789210"));
                assertEquals("audit_log", a.getMetadataValue("indicator"));
                assertEquals("persistence", a.getMetadataValue("technique"));
                assertEquals("iam_anomalous_grant", a.getMetadataValue("rule_name"));
              }
              return null;
            });

    p.run().waitUntilFinish();
  }

  @Test
  public void gatekeeperIgnoreSomeGDTest() throws Exception {
    TestStream<String> s = getTestStream();
    GatekeeperPipeline.GatekeeperOptions opts = getBaseTestOptions();
    opts.setIgnoreGDFindingTypeRegex(new String[] {"Recon:EC2.+"});

    PCollection<Alert> alerts = GatekeeperPipeline.executePipeline(p, p.apply(s), opts);

    PCollection<Long> count = alerts.apply(Count.globally());
    PAssert.that(count).containsInAnyOrder(21L);

    PAssert.that(alerts)
        .satisfies(
            x -> {
              for (Alert a : x) {
                assertNotNull(a.getCategory());
                assertEquals(Alert.AlertSeverity.CRITICAL, a.getSeverity());
                if (a.getCategory().equals("gatekeeper:aws")) {
                  assertFalse(a.getMetadataValue("finding_type").contains("Recon:EC2"));
                }
              }
              return null;
            });

    p.run().waitUntilFinish();
  }

  @Test
  public void gatekeeperDoNotIgnoreEC2InstanceTest() throws Exception {
    TestStream<String> s = getTestStream();
    GatekeeperPipeline.GatekeeperOptions opts = getBaseTestOptions();
    opts.setIgnoreDNSRequestFindingApps(new String[] {});

    PCollection<Alert> alerts = GatekeeperPipeline.executePipeline(p, p.apply(s), opts);

    PCollection<Long> count = alerts.apply(Count.globally());
    PAssert.that(count).containsInAnyOrder(22L);

    p.run().waitUntilFinish();
  }

  @Test
  public void gatekeeperIgnoreEC2InstanceTest() throws Exception {
    TestStream<String> s = getTestStream();
    GatekeeperPipeline.GatekeeperOptions opts = getBaseTestOptions();
    opts.setIgnoreDNSRequestFindingApps(new String[] {"iTalkToCryptoMiningServers"});

    PCollection<Alert> alerts = GatekeeperPipeline.executePipeline(p, p.apply(s), opts);

    PCollection<Long> count = alerts.apply(Count.globally());
    PAssert.that(count).containsInAnyOrder(21L);

    p.run().waitUntilFinish();
  }

  @Test
  public void gatekeeperEscalateAllTestWithEmail() throws Exception {
    TestStream<String> s = getTestStream();
    GatekeeperPipeline.GatekeeperOptions opts = getBaseTestOptions();

    opts.setCriticalNotificationEmail("unlucky_dev@mozilla.com");

    opts.setEscalateETDFindingRuleRegex(new String[] {".+"});
    opts.setEscalateGDFindingTypeRegex(new String[] {".+"});

    PCollection<Alert> alerts = GatekeeperPipeline.executePipeline(p, p.apply(s), opts);

    PCollection<Long> count = alerts.apply(Count.globally());
    PAssert.that(count).containsInAnyOrder(22L);

    PAssert.that(alerts)
        .satisfies(
            x -> {
              for (Alert a : x) {
                assertNotNull(a.getMetadataValue("notify_email_direct"));
                assertEquals("unlucky_dev@mozilla.com", a.getMetadataValue("notify_email_direct"));
              }
              return null;
            });

    p.run().waitUntilFinish();
  }

  @Test
  public void gatekeeperImplicitEscalateAllTestWithEmail() throws Exception {
    TestStream<String> s = getTestStream();
    GatekeeperPipeline.GatekeeperOptions opts = getBaseTestOptions();

    opts.setCriticalNotificationEmail("unlucky_dev@mozilla.com");

    PCollection<Alert> alerts = GatekeeperPipeline.executePipeline(p, p.apply(s), opts);

    PCollection<Long> count = alerts.apply(Count.globally());
    PAssert.that(count).containsInAnyOrder(22L);

    PAssert.that(alerts)
        .satisfies(
            x -> {
              for (Alert a : x) {
                assertNotNull(a.getMetadataValue("notify_email_direct"));
                assertEquals("unlucky_dev@mozilla.com", a.getMetadataValue("notify_email_direct"));
              }
              return null;
            });

    p.run().waitUntilFinish();
  }

  @Test
  public void gatekeeperImplicitEscalateAllTestNoEmail() throws Exception {
    TestStream<String> s = getTestStream();
    GatekeeperPipeline.GatekeeperOptions opts = getBaseTestOptions();

    PCollection<Alert> alerts = GatekeeperPipeline.executePipeline(p, p.apply(s), opts);

    PCollection<Long> count = alerts.apply(Count.globally());
    PAssert.that(count).containsInAnyOrder(22L);

    PAssert.that(alerts)
        .satisfies(
            x -> {
              for (Alert a : x) {
                assertNull(a.getMetadataValue("notify_email_direct"));
              }
              return null;
            });

    p.run().waitUntilFinish();
  }

  @Test
  public void gatekeeperIgnoreSomeAndEscalateSomeTest() throws Exception {
    TestStream<String> s = getTestStream();
    GatekeeperPipeline.GatekeeperOptions opts = getBaseTestOptions();

    opts.setCriticalNotificationEmail("unlucky_dev@mozilla.com");

    // AWS: ignore all recon findings for EC2 and escalate all Trojan or Backdoor findings
    opts.setIgnoreGDFindingTypeRegex(new String[] {"Recon:EC2.+"});
    opts.setEscalateGDFindingTypeRegex(new String[] {"Trojan.+", "Backdoor.+"});
    // GCP: escalate all findings for ETD
    opts.setEscalateETDFindingRuleRegex(new String[] {".+"});

    PCollection<Alert> alerts = GatekeeperPipeline.executePipeline(p, p.apply(s), opts);

    PCollection<Long> count = alerts.apply(Count.globally());
    PAssert.that(count).containsInAnyOrder(21L);

    PAssert.that(alerts)
        .satisfies(
            x -> {
              for (Alert a : x) {
                if (a.getCategory().equals("gatekeeper:aws")) {
                  // check ignored regex was ignored
                  assertFalse(a.getMetadataValue("finding_type").contains("Recon:EC2"));
                  // check escalate regex matches were escalated
                  if (a.getMetadataValue("finding_type").contains("Trojan")
                      || a.getMetadataValue("finding_type").contains("Backdoor")) {
                    assertNotNull(a.getMetadataValue("notify_email_direct"));
                    assertEquals(
                        "unlucky_dev@mozilla.com", a.getMetadataValue("notify_email_direct"));
                  } else {
                    assertNull(a.getMetadataValue("notify_email_direct"));
                  }
                }
                if (a.getCategory().equals("gatekeeper:gcp")) {
                  // check escalate regex matches were escalated
                  assertNotNull(a.getMetadataValue("notify_email_direct"));
                  assertEquals(
                      "unlucky_dev@mozilla.com", a.getMetadataValue("notify_email_direct"));
                }
              }
              return null;
            });

    p.run().waitUntilFinish();
  }

  @Test
  public void gatekeeperEscalateAllTestNoEmail() throws Exception {
    TestStream<String> s = getTestStream();
    GatekeeperPipeline.GatekeeperOptions opts = getBaseTestOptions();

    opts.setEscalateETDFindingRuleRegex(new String[] {".+"});
    opts.setEscalateGDFindingTypeRegex(new String[] {".+"});

    PCollection<Alert> alerts = GatekeeperPipeline.executePipeline(p, p.apply(s), opts);

    PCollection<Long> count = alerts.apply(Count.globally());
    PAssert.that(count).containsInAnyOrder(22L);

    PAssert.that(alerts)
        .satisfies(
            x -> {
              for (Alert a : x) {
                assertNull(a.getMetadataValue("notify_email_direct"));
              }
              return null;
            });

    p.run().waitUntilFinish();
  }

  @Test
  public void gatekeeperSuppressRepeatedGDFindingsOneInstant() throws Exception {
    String[] gd =
        TestUtil.getTestInputArray(
            "/testdata/gatekeeper/guardduty-sample-findings-with-duplicates.txt");

    TestStream<String> s =
        TestStream.create(StringUtf8Coder.of())
            .advanceWatermarkTo(new Instant(0L))
            .addElements(gd[0], Arrays.copyOfRange(gd, 1, gd.length))
            .advanceWatermarkToInfinity();
    GatekeeperPipeline.GatekeeperOptions opts = getBaseTestOptions();

    PCollection<Alert> alerts = GatekeeperPipeline.executePipeline(p, p.apply(s), opts);

    // the sample data contains 5 findings in total, 2 share one id, 3 share another.
    // if all of these findings are processed within the default suppression window (15 mins) we
    // should get 2 alerts
    PAssert.that(alerts.apply(Count.globally())).containsInAnyOrder(2L);

    p.run().waitUntilFinish();
  }

  @Test
  public void gatekeeperSuppressRepeatedETDFindingsOneInstant() throws Exception {
    String[] gd =
        TestUtil.getTestInputArray("/testdata/gatekeeper/etd-sample-findings-with-duplicates.txt");

    TestStream<String> s =
        TestStream.create(StringUtf8Coder.of())
            .advanceWatermarkTo(new Instant(0L))
            .addElements(gd[0], Arrays.copyOfRange(gd, 1, gd.length))
            .advanceWatermarkToInfinity();
    GatekeeperPipeline.GatekeeperOptions opts = getBaseTestOptions();

    PCollection<Alert> alerts = GatekeeperPipeline.executePipeline(p, p.apply(s), opts);

    // the sample data contains 5 findings in total, 2 share one project id, 3 share another.
    // if all of these findings are processed within the default suppression window (15 mins) we
    // should get 2 alerts
    PAssert.that(alerts.apply(Count.globally())).containsInAnyOrder(2L);

    p.run().waitUntilFinish();
  }
}
