package com.mozilla.secops.customs;

import com.mozilla.secops.alert.Alert;
import java.util.ArrayList;
import org.apache.beam.sdk.io.gcp.pubsub.PubsubIO;
import org.apache.beam.sdk.transforms.DoFn;
import org.apache.beam.sdk.transforms.PTransform;
import org.apache.beam.sdk.transforms.ParDo;
import org.apache.beam.sdk.values.PCollection;
import org.apache.beam.sdk.values.PDone;

/**
 * Convert {@link Alert} objects generated by pipeline to {@link CustomsAlert} and submit them over
 * Pubsub.
 */
public class CustomsNotification extends PTransform<PCollection<String>, PDone> {
  private static final long serialVersionUID = 1L;

  private final String topic;

  /**
   * Initialize new CustomsNotification
   *
   * @param options Pipeline options
   */
  public CustomsNotification(Customs.CustomsOptions options) {
    topic = options.getCustomsNotificationTopic();
  }

  @Override
  public PDone expand(PCollection<String> col) {
    return col.apply(
            ParDo.of(
                new DoFn<String, String>() {
                  private static final long serialVersionUID = 1L;

                  @ProcessElement
                  public void processElement(ProcessContext c) {
                    Alert a = Alert.fromJSON(c.element());
                    ArrayList<CustomsAlert> ca = CustomsAlert.fromAlert(a);
                    if (ca == null) {
                      return;
                    }
                    for (CustomsAlert i : ca) {
                      c.output(i.toJSON());
                    }
                  }
                }))
        .apply(PubsubIO.writeStrings().to(topic));
  }
}
